using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FileInOut.Input
{
    [Serializable]
    enum UnvFeDescriptorId
    {
        Rod = 11,
        LinearBeam = 21,
        TaperedBeam = 22,
        CurvedBeam = 23,
        ParabolicBeam = 24,
        StraightPipe = 31,
        CurvedPipe = 32,
        PlaneStressLinearTriangle = 41,
        PlaneStressParabolicTriangle = 42,
        PlaneStressCubicTriangle = 43,
        PlaneStressLinearQuadrilateral = 44,
        PlaneStressParabolicQuadrilateral = 45,
        PlaneStressCubicQuadrilateral = 46,
        PlaneStrainLinearTriangle = 51,
        PlaneStrainParabolicTriangle = 52,
        PlaneStrainCubicTriangle = 53,
        PlaneStrainLinearQuadrilateral = 54,
        PlaneStrainParabolicQuadrilateral = 55,
        PlaneStrainCubicQuadrilateral = 56,
        PlateLinearTriangle = 61,
        PlateParabolicTriangle = 62,
        PlateCubicTriangle = 63,
        PlateLinearQuadrilateral = 64,
        PlateParabolicQuadrilateral = 65,
        PlateCubicQuadrilateral = 66,
        MembraneLinearQuadrilateral = 71,
        MembraneParabolicTriangle = 72,
        MembraneCubicTriangle = 73,
        MembraneLinearTriangle = 74,
        MembraneParabolicQuadrilateral = 75,
        MembraneCubicQuadrilateral = 76,
        AxisymetricSolidLinearTriangle = 81,
        AxisymetricSolidParabolicTriangle = 82,
        AxisymetricSolidLinearQuadrilateral = 84,
        AxisymetricSolidParabolicQuadrilateral = 85,
        ThinShellLinearTriangle = 91,
        ThinShellParabolicTriangle = 92,
        ThinShellCubicTriangle = 93,
        ThinShellLinearQuadrilateral = 94,
        ThinShellParabolicQuadrilateral = 95,
        ThinShellCubicQuadrilateral = 96,
        ThickShellLinearWedge = 101,
        ThickShellParabolicWedge = 102,
        ThickShellCubicWedge = 103,
        ThickShellLinearBrick = 104,
        ThickShellParabolicBrick = 105,
        ThickShellCubicBrick = 106,
        SolidLinearTetrahedron = 111,
        SolidLinearWedge = 112,
        SolidParabolicWedge = 113,
        SolidCubicWedge = 114,
        SolidLinearBrick = 115,
        SolidParabolicBrick = 116,
        SolidCubicBrick = 117,
        SolidParabolicTetrahedron = 118,
        RigidBar = 121,
        RigidElement = 122,
        NodeToNodeTranslational = 136,
        NodeToNodeRotational = 137,
        NodeToGroundTranslational = 138,
        NodeToGroundRotational = 139,
        NodeToNodeDamper = 141,
        NodeToGoundDamper = 142,
        NodeToNodeGap = 151,
        NodeToGroundGap = 152,
        LumpedMass = 161,
        AxisymetricLinearShell = 171,
        AxisymetricParabolicShell = 172,
        Constraint = 181,
        PlasticColdRunner = 191,
        PlasticHotRunner = 192,
        PlasticWaterLine = 193,
        PlasticFountain = 194,
        PlasticBaffle = 195,
        PlasticRodHeater = 196,
        LinearNodeToNodeInterface = 201,
        LinearEdgeToEdgeInterface = 202,
        ParabolicEdgeToEdgeInterface = 203,
        LinearFaceToFaceInterface = 204,
        ParabolicFaceToFaceInterface = 208,
        LinearAxisymmetricInterface = 212,
        ParabolicAxisymmetricInterface = 213,
        LinearRigidSurface = 221,
        ParabolicRigidSurface = 222,
        AxisymetricLinearRigidSurface = 231,
        AxisymetricParabolicRigidSurface = 232
    }


}